Repository miaowware/qrm2, pull requests merged in 2019-12, with the labels that each got.

#117 Update callsign_info.py
  resources/callsign_info.py
Labels: bug

#104 add command to echo a message as the bot in a channel
  exts/base.py
Labels: enhancement

#118 convert all embed creation to embed_factory
  common.py
  exts/ae7q.py
  exts/base.py
  exts/grid.py
  exts/ham.py
  exts/image.py
  exts/lookup.py
  exts/morse.py
  exts/qrz.py
  exts/study.py
  exts/weather.py
  main.py
  resources/callsign_info.py
Labels: enhancement

#121 add server shield to readme
  README.md
Labels: documentation

#126 fix commands that do not use embeds
  exts/ae7q.py
  exts/morse.py
  exts/study.py
Labels: refactor

#125 change embed = embed.add_field() to embed.add_field()
  exts/base.py
  exts/study.py
Labels: code cleanup

#127 add reactions on keywords functionality
  main.py
  templates/data/options.py
Labels: enhancement

#128 qrz: handle addresses that are only whitespace
  exts/qrz.py
Labels: bug

#129 modify playing status so it changes based on time of day
  main.py
  requirements.txt
  templates/data/options.py
Labels: enhancement

#131 combine all aiohttp operations into a single session
  common.py
  exts/ae7q.py
  exts/image.py
  exts/qrz.py
  exts/study.py
  exts/weather.py
  main.py
Labels: refactor

#133 Removed an unused f-string
  exts/weather.py
Labels: code cleanup

#132 Metadata update!
  CHANGELOG.md
  common.py
  dev-notes/metadata-format.md
  exts/image.py
  main.py
  resources/images/map/cqmap.png
  resources/images/map/itumap.png
  resources/images/map/racmap.png
  resources/img/bandcharts/ca.png
  resources/img/bandcharts/cn.png
  resources/img/bandcharts/meta.json
  resources/img/bandcharts/mx.png
  resources/img/bandcharts/nl.png
  resources/img/bandcharts/us.png
  resources/img/maps/arrl-rac.png
  resources/img/maps/cn.png
  resources/img/maps/meta.json
  resources/img/maps/us.png
  templates/data/options.py
Labels: documentation, enhancement, refactor

#136 official server in info command
  README.md
  exts/base.py
  info.py
Labels: documentation, enhancement

#137 Phonetics refacAtor
  exts/fun.py
  exts/ham.py
  exts/morse.py
  resources/morse.json
  resources/morse.py
  resources/phonetics.py
  resources/qcodes.json
  resources/qcodes.py
Labels: enhancement, refactor

#138 correct some line continuations
  exts/ae7q.py
  exts/base.py
  exts/grid.py
  exts/lookup.py
  exts/qrz.py
  exts/study.py
Labels: code cleanup

#143 Fix unclosed files (BytesIO)
  exts/qrz.py
Labels: bug, refactor
