Repository miaowware/qrm2, pull requests merged in 2020-09, with the labels that each got.

#245 update docker documentation to mention github registry
  README-DOCKER.md
Labels: Docker, documentation, easy

#240 Add dev-requirements.txt
  dev-requirements.txt
Labels: enhancement

#244 add canadian callsign info, improve the prefix info data system
  CHANGELOG.md
  common.py
  exts/ham.py
  resources/callsign_info.py
  resources/callsigninfos/__init__.py
  resources/callsigninfos/ca.py
  resources/callsigninfos/us.py
Labels: enhancement

#247 added `?worksplit` command
  CHANGELOG.md
  common.py
  exts/fun.py
  resources/img/worksplit.jpg
Labels: easy, enhancement

#219 Contribution and PR Guidelines
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#248 add cq zone, itu zone and region, canadian maps
  CHANGELOG.md
  dev-notes/image-processing.md
  dev-notes/metadata-format.md
  resources/img/maps/arrl-rac.png
  resources/img/maps/ca.png
  resources/img/maps/cq-zones.png
  resources/img/maps/itu-regions.png
  resources/img/maps/itu-zones.png
  resources/img/maps/meta.json
Labels: enhancement

#249 fix displaying multiple prefixes, add option to display ?help in status
  CHANGELOG.md
  exts/base.py
  main.py
  templates/data/options.py
Labels: bug, easy, enhancement

#252 add dev targets to makefile
  Makefile
Labels: easy

#250 add a decibel conversion command
  CHANGELOG.md
  exts/dbconv.py
  templates/data/options.py
Labels: enhancement
