Repository miaowware/qrm2, pull requests merged in 2020-02, with the labels that each got.

#199 New year linting
  CHANGELOG.md
  common.py
  exts/ae7q.py
  exts/base.py
  exts/fun.py
  exts/grid.py
  exts/ham.py
  exts/image.py
  exts/lookup.py
  exts/morse.py
  exts/qrz.py
  exts/study.py
  exts/weather.py
  info.py
  main.py
  resources/callsign_info.py
  resources/morse.py
  resources/phonetics.py
  resources/qcodes.py
  resources/study.py
  templates/data/options.py
  utils/connector.py
Labels: code cleanup

#200 remove extra comma in pfx invalid input handler
  CHANGELOG.md
  exts/ham.py
Labels: bug, easy

#204 Fix HamStudy image error
  CHANGELOG.md
  dev-notes/test_pool_E5C14.json
  exts/study.py
Labels: bug, easy, priority-high

#205 Added/fixed/removed typing managers
  CHANGELOG.md
  exts/fun.py
  exts/grid.py
  exts/ham.py
  exts/lookup.py
  exts/morse.py
  exts/qrz.py
Labels: bug, easy, enhancement

#207 Bump version + changelog (2.2.2)
  CHANGELOG.md
  info.py
Labels: documentation
