Repository miaowware/qrm2, pull requests merged in 2020-10, with the labels that each got.

#260 Create developer guide, remove issue/pr templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  DEVELOPING.md
Labels: documentation

#269 Made bot work with new Intents system + only cache needed things
  CHANGELOG.md
  dev-requirements.txt
  main.py
  requirements.txt
Labels: bug, enhancement, priority-high

#272 add/update workflows
  .github/workflows/docker.yml
  .github/workflows/release.yml
Labels: easy

#265 update docker documentation to remove docker hub mentions
  README-DOCKER.md
Labels: Docker, documentation

#273 fix error in workflow
  .github/workflows/docker.yml
Labels: Docker, bug, easy

#280 add deploy workflow job
  .github/workflows/docker.yml
Labels: Docker

#281 oops
  .github/workflows/docker.yml
Labels: Docker, priority-high

#278 fixed qsl/lotw status being incorrectly shown
  CHANGELOG.md
  exts/qrz.py
Labels: bug, easy, hacktoberfest-accepted

#258 move CallsignInfoData to resources/callsign_info
  common.py
  resources/callsign_info.py
Labels: blocked, easy, hacktoberfest-accepted, refactor

#276 Release fixes
  .github/workflows/release.yml
Labels: bug, easy

#257 convert Unit into a dataclass, move parse to converter
  exts/dbconv.py
Labels: easy, hacktoberfest-accepted, refactor

#286 Unpinned the versions of most dependencies
  requirements.txt
Labels: enhancement, hacktoberfest-accepted

#290 Fixed numerous small potential bugs
  common.py
  main.py
Labels: code cleanup

#301 Yes, this is a PR to remove a newline
  exts/base.py
Labels: code cleanup

#297 Switch to sending an URL instead of fetching images
  exts/image.py
  exts/weather.py
Labels: bug, enhancement, hacktoberfest-accepted, refactor

#298 Changed the intents and member cache
  main.py
Labels: enhancement, hacktoberfest-accepted

#300 Moved paths to pathlib
  exts/fun.py
  exts/lookup.py
Labels: hacktoberfest-accepted, refactor
