Repository miaowware/qrm2, pull requests merged in 2020-12, with the labels that each got.

#313 add reactions intent
  main.py
Labels: bug, priority-high

#314 Addded a "nonce" to the greyline URL to force discord to reload the c…
  CHANGELOG.md
  exts/image.py
Labels: bug

#319 Changed the greyline colour theme
  CHANGELOG.md
  exts/image.py
Labels: easy, enhancement

#326 convert GridCog to use gridtools
  CHANGELOG.md
  exts/grid.py
  requirements.txt
Labels: refactor
