Repository miaowware/qrm2, pull requests merged in 2020-01, with the labels that each got.

#147 Better command error handling
  CHANGELOG.md
  common.py
  exts/base.py
  main.py
Labels: enhancement

#149 v2.1.0 prep for release
  CHANGELOG.md
  info.py
Labels: documentation

#156 add category to prefixes command
  exts/ham.py
Labels: documentation

#155 add --link flag to only link the qrz page (rather than embed)
  CHANGELOG.md
  exts/qrz.py
Labels: enhancement

#157 changed changelog command to accept a version as argument
  CHANGELOG.md
  exts/base.py
Labels: enhancement

#158 Ae7q bugfixes
  CHANGELOG.md
  exts/ae7q.py
Labels: bug

#159 add trustee field to qrz
  CHANGELOG.md
  exts/qrz.py
Labels: bug

#161 update copyright for the new year
  README.md
  common.py
  exts/ae7q.py
  exts/base.py
  exts/fun.py
  exts/grid.py
  exts/ham.py
  exts/image.py
  exts/lookup.py
  exts/morse.py
  exts/qrz.py
  exts/study.py
  exts/weather.py
  info.py
  main.py
  resources/callsign_info.py
  resources/morse.py
  resources/phonetics.py
  resources/qcodes.py
Labels: documentation

#163 [FIX] aiohttp DeprecationWarning
  exts/ae7q.py
  exts/image.py
  exts/qrz.py
  exts/study.py
  exts/weather.py
  main.py
  utils/__init__.py
  utils/connector.py
Labels: bug, priority-high, refactor

#165 echo: New converters for arguments
  common.py
  exts/base.py
Labels: enhancement

#166 Added aliases for extctl and subcommands
  main.py
Labels: enhancement

#162 refactor ae7q call, add other ae7q query types
  CHANGELOG.md
  exts/ae7q.py
Labels: enhancement, refactor

#176 Mini-fix: extraneous warning reaction on messages starting with "??"
  CHANGELOG.md
  main.py
Labels: bug

#175 Fixed bad file/embed sending logic in multiple commands
  exts/image.py
  exts/weather.py
Labels: bug, enhancement, refactor

#177 Hamstudy refactor
  CHANGELOG.md
  common.py
  exts/study.py
  resources/study.py
Labels: enhancement, refactor

#180 add aliases to restart and shutdown commands
  main.py
Labels: easy, enhancement

#183 Improved error handling in commands
  CHANGELOG.md
  common.py
  exts/ae7q.py
  exts/grid.py
  exts/image.py
  exts/morse.py
  exts/study.py
  exts/weather.py
  main.py
Labels: enhancement, refactor

#178 Verify checks in help commands
  common.py
  exts/base.py
  main.py
Labels: enhancement
