Repository miaowware/qrm2, pull requests merged in 2021-03, with the labels that each got.

#348 hamstudy improvements
  CHANGELOG.md
  common.py
  exts/study.py
Labels: code cleanup, enhancement

#346 Validate inputs for ?ae7q and ?qrz commands
  exts/ae7q.py
  exts/qrz.py
Labels: bug

#349 fix issue with pushing docker images to ghcr
  .github/workflows/docker.yml
Labels: Docker, bug

#354 Prefixes and the ?help command
  CHANGELOG.md
  exts/base.py
Labels: bug, enhancement

#358 Donate/Invite commands
  CHANGELOG.md
  exts/base.py
  templates/data/options.py
Labels: enhancement

#359 convert qrzcog to use qrztools
  CHANGELOG.md
  exts/qrz.py
  requirements.txt
  templates/data/options.py
Labels: enhancement, refactor

#360 add failsafe to not show invite if bot is not public
  exts/base.py
Labels: enhancement

#364 bump python to >=3.9, bump d.py to ~=1.6.0
  .github/workflows/linting.yml
  CHANGELOG.md
  DEVELOPING.md
  Dockerfile
  Makefile
  README.md
  requirements.txt
  run.sh
Labels: Docker, documentation, enhancement

#363 add support for plugins
  .gitignore
  Makefile
  exts/base.py
  main.py
Labels: enhancement

#366 Added and switched to the Resource Manager
  .dockerignore
  CHANGELOG.md
  common.py
  dev-notes/rs_index_schema.json
  dev-notes/test_resource_manager.py
  exts/fun.py
  exts/ham.py
  exts/image.py
  exts/morse.py
  main.py
  requirements.txt
  resource_schemas.py
  resources/img/bandcharts/au.png
  resources/img/bandcharts/ca.png
  resources/img/bandcharts/cn.png
  resources/img/bandcharts/it_hf.png
  resources/img/bandcharts/it_shf.png
  resources/img/bandcharts/it_vhf.png
  resources/img/bandcharts/jp.png
  resources/img/bandcharts/meta.json
  resources/img/bandcharts/mx.png
  resources/img/bandcharts/nl.png
  resources/img/bandcharts/us.png
  resources/img/maps/arrl-rac.png
  resources/img/maps/ca.png
  resources/img/maps/cn.png
  resources/img/maps/cq-zones.png
  resources/img/maps/itu-regions.png
  resources/img/maps/itu-zones.png
  resources/img/maps/meta.json
  resources/img/maps/us.png
  resources/img/worksplit.jpg
  resources/morse.py
  resources/phonetics.py
  resources/qcodes.py
  resources/words
  templates/data/options.py
  utils/resources_manager.py
  utils/resources_models.py
Labels: enhancement

#369 correct README links
  README.md
Labels: documentation

#371 add ?tex command
  CHANGELOG.md
  exts/tex.py
  templates/data/options.py
Labels: enhancement

#375 add latex resource to main.py
  main.py
Labels: bug

#378 add system dependencies to README and DEVELOPING
  DEVELOPING.md
  README.md
Labels: documentation

#379 make ?xkcd only accept ints as arg
  CHANGELOG.md
  exts/fun.py
Labels: bug

#381 Moved map/plan code to a single function
  CHANGELOG.md
  common.py
  exts/image.py
Labels: refactor
