Repository miaowware/qrm2, pull requests merged in 2021-01, with the labels that each got.

#330 Added MUF and foF2 maps
  exts/propagation.py
  requirements.txt
  templates/data/options.py
Labels: enhancement

#329 0x5c did an oopsie
  main.py
Labels: bug

#333 Renamed ?cond to ?solar
  CHANGELOG.md
  exts/weather.py
Labels: enhancement

#334 Cleaned-up usused aiohttp sessions
  exts/weather.py
Labels: code cleanup

#327 migrate from github packages to github container registry
  .github/workflows/docker.yml
Labels: Docker, frozen

#335 Fixed ?greyline caching (set date url param)
  CHANGELOG.md
  exts/image.py
Labels: bug

#337 add missing packages to docker dependencies
  Dockerfile
Labels: bug

#340 add METAR and TAF commands
  CHANGELOG.md
  exts/weather.py
Labels: enhancement

#343 add qrm-resources contribution info to ?info, ?issue, and readme
  README.md
  exts/base.py
  info.py
Labels: documentation, enhancement

#344 add the ability to select an element to hamstudy
  CHANGELOG.md
  exts/study.py
Labels: enhancement

#342 add git commit to info output
  exts/base.py
Labels: enhancement
