Repository miaowware/qrm2, pull requests merged in 2021-04, with the labels that each got.

#409 Added ?miltime command
  exts/time.py
Labels: enhancement

#410 Renamed clock emoji to "stopwatch", added proper clock
  common.py
  exts/study.py
Labels: bug, code cleanup

#411 bump copyright to include 2021
  README.md
  exts/ae7q.py
  exts/base.py
  exts/dbconv.py
  exts/grid.py
  exts/propagation.py
  exts/study.py
  info.py
  resources/callsign_info.py
  resources/callsigninfos/ca.py
  resources/callsigninfos/us.py
  resources/study.py
  utils/connector.py
Labels: documentation

#417 make help command sort by category
  common.py
  exts/base.py
Labels: enhancement

#420 Fixed ?call crash on empty adress fields
  CHANGELOG.md
  exts/callsign.py
Labels: bug

#422 fix issue with help command/categories
  CHANGELOG.md
  exts/base.py
Labels: bug

#423 update changelog/version for 2.7.2
  CHANGELOG.md
  info.py
Labels: documentation

#424 fix issue with help cmd not showing all cmds, bump to 2.7.3
  CHANGELOG.md
  exts/base.py
  info.py
Labels: bug
