Repository miaowware/qrm2, pull requests merged in 2023-01, with the labels that each got.

#456 exts/callsign: simplify stringification, fix data validation
  exts/callsign.py
Labels: bug, easy, Skip-Changelog

#460 exts/propagation: Remove deprecated ?solarweather aliases
  CHANGELOG.md
  exts/propagation.py
Labels: deprecation

#458 exts/study: fix in DMs
  CHANGELOG.md
  exts/study.py
  main.py
Labels: bug

#465 .github/workflows/release.yml: move to ncipollo/create-release action
  .github/workflows/release.yml
Labels: bug, Skip-Changelog

#468 Embed factory/pycord fixes
  CHANGELOG.md
  common.py
Labels: bug, priority-high

#469 exts/callsign: unworkaround some things solved in CLT 1.1.0
  CHANGELOG.md
  exts/callsign.py
  requirements.txt
Labels: bug, code cleanup

#471 rel 2.9.1
  CHANGELOG.md
  README.md
  common.py
  exts/ae7q.py
  exts/base.py
  exts/callsign.py
  exts/codes.py
  exts/contests.py
  exts/dbconv.py
  exts/dxcc.py
  exts/fun.py
  exts/grid.py
  exts/image.py
  exts/land_weather.py
  exts/morse.py
  exts/prefixes.py
  exts/propagation.py
  exts/study.py
  exts/tex.py
  exts/time.py
  info.py
  main.py
  resource_schemas.py
  resources/callsign_info.py
  resources/callsigninfos/ca.py
  resources/callsigninfos/us.py
  resources/study.py
  utils/connector.py
  utils/resources_manager.py
  utils/resources_models.py
Labels: documentation

#472 exts/callsign: fix mail qsl display
  exts/callsign.py
Labels: bug, easy, Skip-Changelog

#457 Add NOAA D-RAP map to propagation plugin ?drapmap
  CHANGELOG.md
  exts/propagation.py
Labels: enhancement
